import streamlit as st
from datetime import datetime
import pandas as pd
from fpdf import FPDF
import tempfile
import os

# Importy z Twojego silnika systemowego
from core import fetch_data, append_data, get_next_daily_number, get_gsheets_client
# Importy z nowego silnika wycen
from pricing import calculate_vantage_price, TRANSIT_DAYS

# --- GENERATOR PDF (ZOPTYMALIZOWANY) ---
def generate_quick_pdf(dane):
    def sanitize(text):
        replacements = {'ą':'a', 'ć':'c', 'ę':'e', 'ł':'l', 'ń':'n', 'ó':'o', 'ś':'s', 'ź':'z', 'ż':'z',
                        'Ą':'A', 'Ć':'C', 'Ę':'E', 'Ł':'L', 'Ń':'N', 'Ó':'O', 'Ś':'S', 'Ź':'Z', 'Ż':'Z'}
        for pl, eng in replacements.items():
            text = str(text).replace(pl, eng)
        return text

    pdf = FPDF()
    pdf.add_page()
    
    # Logo SQM
    try:
        pdf.image("logosqm.jpg", 10, 8, 45)
    except:
        pass
        
    pdf.set_xy(10, 35)
    pdf.set_font("Arial", 'B', 15)
    pdf.cell(0, 10, sanitize("ZLECENIE TRANSPORTOWE / TRANSPORT ORDER"), ln=True, align="C")
    pdf.set_font("Arial", '', 9)
    pdf.cell(0, 5, sanitize(f"DATA WYSTAWIENIA: {datetime.now().strftime('%d.%m.%Y')} | REF: {dane.get('nr', '')}"), ln=True, align="C")
    pdf.ln(10)

    def add_row(left, right, bold=False):
        pdf.set_font("Arial", 'B', 8)
        pdf.set_fill_color(240, 240, 240)
        x, y = pdf.get_x(), pdf.get_y()
        pdf.rect(x, y, 60, 10, style='DF')
        pdf.set_xy(x, y + 2)
        pdf.cell(60, 5, sanitize(left), align='C')
        
        pdf.set_xy(x + 60, y)
        pdf.rect(x + 60, y, 130, 10)
        pdf.set_font("Arial", 'B' if bold else '', 9)
        pdf.set_xy(x + 62, y + 2)
        pdf.cell(126, 5, sanitize(str(right)))
        pdf.set_xy(10, y + 10)

    add_row("PRZEWOŹNIK", dane.get('przewoznik', ''), True)
    add_row("AUTO / KIEROWCA", dane.get('auto', ''), True)
    add_row("CENA TOTAL (NETTO)", f"{dane.get('stawka', '')} {dane.get('waluta', 'EUR')}", True)
    
    if dane.get('typ_zlecenia') == "Pełny event" and float(dane.get('postoj', 0)) > 0:
        add_row("STAWKA ZA POSTÓJ / DZIEŃ", f"{dane.get('postoj', '')} {dane.get('waluta', 'EUR')}")
        
    pdf.ln(5)
    add_row("ZAŁADUNEK (MIEJSCE)", dane.get('zaladunek', ''))
    add_row("ZAŁADUNEK (DATA)", dane.get('data_zal', ''))
    pdf.ln(5)
    add_row("ROZŁADUNEK (MIEJSCE)", dane.get('rozladunek', ''))
    add_row("ROZŁADUNEK (DATA)", dane.get('data_roz', ''))
    
    if dane.get('typ_zlecenia') == "Pełny event":
        pdf.ln(5)
        add_row("ODBIÓR PUSTYCH (EMPTIES)", dane.get('data_emp_in', ''))
        add_row("ODBIÓR PEŁNYCH / POWRÓT", dane.get('data_emp_out', ''))
        
    pdf.ln(5)
    add_row("WAGA ŁADUNKU", f"{dane.get('waga', '')} kg")
    add_row("WARTOŚĆ TOWARU", f"{dane.get('wartosc', '')} PLN")
    add_row("UWAGI", dane.get('uwagi', ''))
    
    pdf.set_y(-30)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, "Generated by Vortex Nexus Engine - Professional Logistics Solutions", 0, 0, 'C')

    return bytes(pdf.output(dest='S').encode('latin1'))

# --- INTERFEJS UŻYTKOWNIKA ---
st.set_page_config(page_title="Szybkie Zlecenie", page_icon="🚀", layout="centered")

st.markdown("<h2 style='text-align: center; color: #38bdf8;'>🚀 Szybkie Zlecenie Targowe</h2>", unsafe_allow_html=True)

# Pobieranie słowników
with st.spinner("Synchronizacja..."):
    df_przewoznicy = fetch_data("Zleceniobiorcy")
    df_projekty = fetch_data("Projekty")
    df_miejsca = fetch_data("Miejsca")

lista_przewoznikow = df_przewoznicy['Skrócona Nazwa'].tolist() if not df_przewoznicy.empty else ["Brak danych"]
lista_eventow = df_projekty['Nazwa Eventu'].dropna().unique().tolist() if not df_projekty.empty else ["Brak"]
lista_miejsc_baza = df_miejsca['Nazwa do listy'].tolist() if not df_miejsca.empty else []
opcje_lokalizacji = ["Magazyn SQM Komorniki"] + lista_miejsc_baza + ["INNE (wpisz ręcznie)"]

# Główny przełącznik trybu
st.markdown("<br>", unsafe_allow_html=True)
typ_zlecenia = st.radio("Wybierz model operacyjny:", ["Tylko dostawa", "Pełny event"], horizontal=True)

# SEKCOJA 1: TRASA I WYCENA VANTAGE
with st.container(border=True):
    st.markdown("#### 1. Parametry trasy i Analiza Vantage")
    lista_miast_vantage = sorted(list(TRANSIT_DAYS.keys()))
    
    c_city, c_weight = st.columns([3, 1])
    miasto_docelowe = c_city.selectbox("Miasto docelowe (Vantage Engine):", ["Wybierz miasto..."] + lista_miast_vantage)
    waga = c_weight.number_input("Waga (kg):", min_value=0, step=100, value=1000)
    
    h1, h2 = st.columns(2)
    data_zal = h1.date_input("Planowany załadunek:", datetime.now())
    data_roz = h2.date_input("Planowany rozładunek:", datetime.now())

# Logika podpowiedzi cenowej
sugerowana_stawka = 0.0
sugerowany_przewoznik = "Wybierz..."

if miasto_docelowe != "Wybierz miasto...":
    tryb_ceny = "full" if typ_zlecenia == "Pełny event" else "prop"
    analiza = calculate_vantage_price(miasto_docelowe, waga, data_zal, data_roz, tryb_ceny)
    
    if analiza:
        sugerowana_stawka = float(analiza[0]['cost'])
        sugerowany_przewoznik = analiza[0]['carrier']
        st.info(f"💡 **Vantage AI:** Najlepsza opcja to **{sugerowany_przewoznik}** za ok. **€{sugerowana_stawka:,.2f}**")

# SEKCJA 2: FINANSE I PARTNER
with st.container(border=True):
    st.markdown("#### 2. Kontrahent i Koszty")
    f1, f2, f3, f4 = st.columns([2, 1, 0.8, 1])
    
    przewoznik_final = f1.selectbox("Zleceniobiorca:", [sugerowany_przewoznik] + lista_przewoznikow)
    stawka_final = f2.number_input("Stawka Total:", min_value=0.0, step=50.0, value=sugerowana_stawka)
    waluta = f3.selectbox("Waluta:", ["EUR", "PLN"])
    
    if typ_zlecenia == "Pełny event":
        postoj = f4.number_input("Postój/Dz:", min_value=0, step=50, value=150)
    else:
        postoj = 0

# SEKCJA 3: LOKALIZACJE SZCZEGÓŁOWE
with st.container(border=True):
    st.markdown("#### 3. Dokładne adresy")
    l1, l2 = st.columns(2)
    
    with l1:
        z_sel = st.selectbox("Miejsce startu:", opcje_lokalizacji)
        z_man = st.text_input("Adres załadunku (ręcznie):") if z_sel == "INNE (wpisz ręcznie)" else ""
    with l2:
        r_sel = st.selectbox("Miejsce celu:", opcje_lokalizacji)
        r_man = st.text_input("Adres rozładunku (ręcznie):") if r_sel == "INNE (wpisz ręcznie)" else ""

# SEKCJA 4: HARMONOGRAM I ŁADUNEK
with st.container(border=True):
    st.markdown("#### 4. Detale operacyjne")
    wydarzenie = st.selectbox("Przypisz do projektu:", lista_eventow)
    
    if typ_zlecenia == "Pełny event":
        e1, e2 = st.columns(2)
        data_emp_in = e1.date_input("Odbiór pustych opakowań:")
        data_emp_out = e2.date_input("Załadunek powrotny / Wyjazd:")
    else:
        data_emp_in, data_emp_out = "", ""

    d1, d2 = st.columns(2)
    auto_kierowca = d1.text_input("Auto / Kierowca:", placeholder="np. PO 12345 / Jan Kowalski")
    wartosc_towaru = d2.number_input("Wartość towaru (PLN):", min_value=0, step=5000, value=50000)
    
    u1, u2 = st.columns([3, 1])
    instrukcje = u1.text_input("Instrukcje specjalne:")
    podpis = u2.radio("Podpis:", ["PD", "PK"], horizontal=True)

# AKCJA KOŃCOWA
st.markdown("<br>", unsafe_allow_html=True)
if st.button("⚡ GENERUJ I ZAPISZ ZLECENIE", type="primary", use_container_width=True):
    with st.spinner("Przetwarzanie..."):
        # Ustalanie finalnych adresów
        final_zal = z_man if z_sel == "INNE (wpisz ręcznie)" else z_sel
        final_roz = r_man if r_sel == "INNE (wpisz ręcznie)" else r_sel
        
        # Generowanie numeru zlecenia
        rok, data_kod = datetime.now().strftime('%y'), datetime.now().strftime('%m%d')
        idx = get_next_daily_number(datetime.now().strftime("%Y-%m-%d"))
        pref = str(wydarzenie)[:3].upper() if wydarzenie != "Brak" else "TRG"
        nr_zlecenia = f"{pref}{rok}/{data_kod}/{podpis}{idx:02d}"
        
        # Budowa opisu do bazy
        if typ_zlecenia == "Pełny event":
            historia = f"CYKL: {data_zal} -> {data_roz} | EMPTIES: {data_emp_in} | POWRÓT: {data_emp_out}"
        else:
            historia = f"DOSTAWA: {data_zal} -> {data_roz}"
            
        pelne_uwagi = f"AUTO: {auto_kierowca} || WAGA: {waga}kg | WART: {wartosc_towaru}PLN || {historia} || {instrukcje}"
        
        # Przygotowanie danych do PDF
        paczka_pdf = {
            "typ_zlecenia": typ_zlecenia, "nr": nr_zlecenia, "przewoznik": przewoznik_final,
            "stawka": stawka_final, "waluta": waluta, "postoj": postoj,
            "zaladunek": final_zal, "data_zal": str(data_zal),
            "rozladunek": final_roz, "data_roz": str(data_roz),
            "data_emp_in": str(data_emp_in), "data_emp_out": str(data_emp_out),
            "waga": waga, "wartosc": wartosc_towaru, "auto": auto_kierowca, "uwagi": instrukcje
        }
        
        # Zapis do Google Sheets
        wiersz_db = [
            datetime.now().strftime("%Y-%m-%d %H:%M"), nr_zlecenia, "LOGISTYKA CARGO", przewoznik_final,
            final_zal, final_roz, str(data_zal), str(data_roz), "Elementy Zabudowy",
            "", "", "", "", pelne_uwagi, "", wydarzenie, "TARGI", f"{stawka_final} {waluta}"
        ]
        
        if append_data("Zlecenia", wiersz_db):
            pdf_bytes = generate_quick_pdf(paczka_pdf)
            st.success(f"✅ Zlecenie {nr_zlecenia} zapisane w systemie!")
            st.download_button(
                label="📥 POBIERZ ZLECENIE PDF",
                data=pdf_bytes,
                file_name=f"Zlecenie_{nr_zlecenia.replace('/', '_')}.pdf",
                mime="application/pdf",
                use_container_width=True
            )
