import streamlit as st
from datetime import datetime
from fpdf import FPDF
import qrcode
import tempfile
import os
import hashlib
import difflib
from core import fetch_data, append_data, get_next_daily_number
from pricing import get_all_carrier_rates, TRANSIT_DAYS

# --- GLOBALNY FILTR ZNAKÓW DLA FPDF ---
def pdf_sanitize(text):
    text = str(text)
    replacements = {
        'ą':'a', 'ć':'c', 'ę':'e', 'ł':'l', 'ń':'n', 'ó':'o', 'ś':'s', 'ź':'z', 'ż':'z',
        'Ą':'A', 'Ć':'C', 'Ę':'E', 'Ł':'L', 'Ń':'N', 'Ó':'O', 'Ś':'S', 'Ź':'Z', 'Ż':'Z',
        '€':'EUR', '–':'-', '—':'-', '”':'"', '„':'"', '’':"'", '“':'"', '\xa0':' '
    }
    for pl, eng in replacements.items():
        text = text.replace(pl, eng)
    return text.encode('latin-1', 'ignore').decode('latin-1')

# --- NOWOCZESNY GENERATOR PDF PRO ---
class PRO_TransportOrder(FPDF):
    def __init__(self, watermark_text="SQM", opiekun="PD"):
        super().__init__()
        self.watermark_text = pdf_sanitize(watermark_text)
        self.opiekun = opiekun
        self.primary_color = (25, 118, 210)
        self.dark_text = (40, 40, 40)
        self.light_text = (100, 100, 100)

    def add_watermark(self):
        self.set_font("Arial", 'B', 45)
        self.set_text_color(245, 245, 245) 
        for j in range(80, 297, 45):
            przesuniecie = 35 if (j // 45) % 2 == 0 else 0
            for i in range(-20, 210, 70):
                self.text(i + przesuniecie, j, self.watermark_text)
        self.set_text_color(0, 0, 0)

    def header(self):
        try:
            if os.path.exists("logosqm.png"):
                self.image("logosqm.png", 10, 8, 50)
            elif os.path.exists("logosqm.jpg"):
                self.image("logosqm.jpg", 10, 8, 50)
        except:
            pass
        
        self.set_font("Arial", 'B', 18)
        self.set_text_color(*self.dark_text)
        self.set_xy(65, 12)
        self.cell(105, 8, pdf_sanitize("TRANSPORT ORDER"), ln=True, align='R')
        
        self.set_font("Arial", 'B', 11)
        self.set_text_color(*self.light_text)
        self.set_xy(65, 20)
        self.cell(105, 5, pdf_sanitize("ZLECENIE TRANSPORTOWE"), ln=True, align='R')
        
        self.set_font("Arial", '', 8)
        self.set_text_color(*self.light_text)
        self.set_xy(65, 26)
        self.cell(105, 5, pdf_sanitize("SQM Prosta Spółka Akcyjna | Logistics Department"), ln=True, align='R')
        self.ln(15)

    def footer(self):
        self.set_y(-30)
        self.set_font("Arial", 'I', 10)
        self.set_text_color(*self.primary_color)
        self.cell(0, 5, pdf_sanitize("Thank you for your cooperation! / Dziękujemy za współpracę!"), ln=True, align='C')
        
        self.set_font("Arial", '', 8)
        self.set_text_color(*self.light_text)
        
        if self.opiekun == "PD":
            email = "piotr.dukiel@sqm.eu"
            telefon = "+48 577 63 63 67"
        else:
            email = "piotr.kaczmarek@sqm.eu"
            telefon = "+48 570 33 02 90"
            
        self.cell(0, 5, pdf_sanitize(f"www.sqm.pl   |   {email}   |   {telefon}"), ln=True, align='C')
        self.cell(0, 5, pdf_sanitize("Document generated by Vorteza Orders dla SQM"), ln=True, align='C')

def generate_pro_pdf(dane):
    pdf = PRO_TransportOrder(opiekun=dane.get('opiekun', 'PD'))
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.add_watermark()

    # KOD QR 
    token_base = f"{dane['nr']}-{dane['przewoznik_nazwa']}-{dane['stawka']}"
    secure_hash = hashlib.md5(token_base.encode()).hexdigest()[:12].upper()
    qr_content = f"SQM-VERIFY: {dane['nr']}\nVALID-HASH: {secure_hash}\nSYSTEM: VORTEX 4.0"
    
    qr = qrcode.QRCode(version=1, box_size=10, border=1)
    qr.add_data(qr_content)
    qr.make(fit=True)
    img_qr = qr.make_image(fill_color="black", back_color="white")
    
    with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
        img_qr.save(tmp, format="PNG")
        qr_path = tmp.name
    pdf.image(qr_path, 175, 10, 25)
    if os.path.exists(qr_path): os.remove(qr_path)

    # BLOKI: REF & DATE
    pdf.set_xy(10, 40)
    pdf.set_font("Arial", 'B', 9)
    pdf.set_fill_color(25, 118, 210) 
    pdf.set_text_color(255, 255, 255)
    pdf.cell(25, 8, pdf_sanitize(" REF "), border=0, fill=True, align='C')
    pdf.set_fill_color(245, 245, 245)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(60, 8, pdf_sanitize(f" {dane['nr']}"), border=0, fill=True)
    pdf.cell(5, 8, "", border=0) 
    pdf.set_fill_color(25, 118, 210)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(25, 8, pdf_sanitize(" DATE "), border=0, fill=True, align='C')
    pdf.set_fill_color(245, 245, 245)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(60, 8, pdf_sanitize(f" {datetime.now().strftime('%d.%m.%Y')}"), border=0, fill=True)
    pdf.ln(12)

    def draw_section_header(num, title):
        pdf.set_fill_color(25, 118, 210)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(10, 10, pdf_sanitize(str(num).zfill(2)), fill=True, align='C')
        pdf.set_text_color(40, 40, 40)
        pdf.cell(5, 10, "", border=0)
        pdf.cell(0, 10, pdf_sanitize(title), ln=True)
        pdf.ln(2)

    def draw_row(label, val, border_b=True):
        x_start = pdf.get_x()
        y_start = pdf.get_y()
        pdf.set_font("Arial", 'B', 8)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(65, 6, pdf_sanitize(label), border=0)
        pdf.set_font("Arial", 'B', 10)
        pdf.set_text_color(40, 40, 40)
        pdf.set_xy(x_start + 65, y_start + 0.5)
        pdf.multi_cell(125, 5, pdf_sanitize(val), border=0)
        y_end = pdf.get_y() + 1.5
        if border_b:
            pdf.set_draw_color(230, 230, 230)
            pdf.line(10, y_end, 200, y_end)
        pdf.set_xy(10, y_end + 2)

    # 01 PARTIES
    draw_section_header(1, "PARTIES & ASSETS / STRONY I POJAZD")
    draw_row("CONTRACTOR / PRZEWOŹNIK:", dane['przewoznik_detale'])
    draw_row("VEHICLE & DRIVER / AUTO I KIEROWCA:", dane['auto'] if dane['auto'] else "TBA / Do podania")
    draw_row("VALUATION MODEL / TRYB WYCENY:", dane['typ_zlecenia'], border_b=False)
    pdf.ln(4)

    # 02 LOGISTICS TIMELINE
    draw_section_header(2, "LOGISTICS TIMELINE / HARMONOGRAM LOGISTYCZNY")
    draw_row("LOADING PLACE / MIEJSCE ZAŁADUNKU:", dane['zaladunek'])
    draw_row("LOADING DATE / DATA ZAŁADUNKU:", dane['data_zal'])
    draw_row("UNLOADING PLACE / MIEJSCE ROZŁADUNKU:", dane['rozladunek'])
    if dane['typ_zlecenia'] == "Pełny event":
        draw_row("UNLOADING DATE / DATA ROZŁADUNKU:", dane['data_roz'])
        draw_row("EMPTIES IN / ODBIÓR PUSTYCH:", dane['data_emp_in'])
        draw_row("RETURN LOAD / DATA POWROTU:", dane['data_emp_out'], border_b=False)
    else:
        draw_row("UNLOADING DATE / DATA ROZŁADUNKU:", dane['data_roz'], border_b=False)
    pdf.ln(4)

    # 03 FINANCIALS
    draw_section_header(3, "FINANCIALS & CARGO / FINANSE I ŁADUNEK")
    sy = pdf.get_y()
    pdf.set_xy(120, sy); pdf.set_fill_color(25, 118, 210); pdf.rect(120, sy, 80, 25, 'F')
    pdf.set_xy(125, sy + 3); pdf.set_font("Arial", 'B', 8); pdf.set_text_color(255, 255, 255)
    pdf.cell(70, 5, pdf_sanitize("TOTAL NET RATE / KWOTA NETTO"), ln=True)
    pdf.set_xy(125, sy + 10); pdf.set_font("Arial", 'B', 20)
    pdf.cell(70, 10, pdf_sanitize(f"{dane['stawka']} {dane['waluta']}"), ln=True)
    
    pdf.set_xy(10, sy)
    pdf.set_font("Arial", 'B', 8); pdf.set_text_color(100, 100, 100); pdf.cell(55, 5, pdf_sanitize("CARGO TYPE / RODZAJ TOWARU:"), border=0)
    pdf.set_font("Arial", 'B', 10); pdf.set_text_color(40, 40, 40); pdf.set_xy(65, sy); pdf.multi_cell(50, 5, pdf_sanitize("Exhibition Structures / AV Equipment"))
    pdf.set_xy(10, pdf.get_y() + 2)
    pdf.set_font("Arial", 'B', 8); pdf.set_text_color(100, 100, 100); pdf.cell(55, 5, pdf_sanitize("GROSS WEIGHT / WAGA BRUTTO:"), border=0)
    pdf.set_font("Arial", 'B', 10); pdf.set_text_color(40, 40, 40); pdf.set_xy(65, pdf.get_y()); pdf.cell(50, 5, pdf_sanitize(f"{dane['waga']} kg"))
    
    pdf.set_xy(10, sy + 35)
    draw_section_header(4, "SPECIAL PROVISIONS / UWAGI SPECJALNE")
    pdf.set_font("Arial", 'I', 10); pdf.multi_cell(0, 6, pdf_sanitize(dane['uwagi']))

    return bytes(pdf.output(dest='S').encode('latin1'))

# --- INTERFEJS UŻYTKOWNIKA ---
st.set_page_config(page_title="Vorteza PRO", page_icon="🚀", layout="centered")
st.markdown("<h2 style='text-align: center; color: #38bdf8;'>🚀 Szybkie Zlecenie PRO v5.3</h2>", unsafe_allow_html=True)

with st.spinner("Ładowanie telemetrii..."):
    df_projekty = fetch_data("Projekty")
    df_miejsca = fetch_data("Miejsca")
    df_przewoznicy = fetch_data("Zleceniobiorcy")

lista_eventow = df_projekty['Nazwa Eventu'].dropna().unique().tolist() if not df_projekty.empty else ["Brak"]
lista_miejsc_baza = df_miejsca['Nazwa do listy'].tolist() if not df_miejsca.empty else []
opcje_lokalizacji = ["Magazyn SQM Komorniki"] + lista_miejsc_baza + ["INNE (wpisz ręcznie)"]

typ_zlecenia = st.radio("Tryb operacji:", ["Tylko dostawa", "Pełny event"], horizontal=True)

with st.container(border=True):
    st.markdown("#### 1. Kierunek i Harmonogram")
    lista_miast = sorted(list(TRANSIT_DAYS.keys()))
    c1, c2 = st.columns([3, 1])
    miasto_docelowe = c1.selectbox("Miasto docelowe:", ["Wybierz..."] + lista_miast)
    waga = c2.number_input("Waga (kg):", min_value=100, step=100, value=1000)
    d1, d2 = st.columns(2)
    data_zal = d1.date_input("Data załadunku (PL):", datetime.now())
    data_roz = d2.date_input("Data rozładunku (Targi):", datetime.now())
    if typ_zlecenia == "Pełny event":
        h1, h2 = st.columns(2)
        data_emp_in = h1.date_input("Odbiór pustych:")
        data_emp_out = h2.date_input("Powrót / Załadunek:")
    else:
        data_emp_in, data_emp_out = "", ""

slownik_stawek = get_all_carrier_rates(miasto_docelowe, waga, data_zal, data_roz, data_emp_out, typ_zlecenia)

with st.container(border=True):
    st.markdown("#### 2. Wybór Przewoźnika i Koszty")
    zrodlo = st.radio("Typ przewoźnika:", ["Przewoźnik stały (Cennik)", "Przewoźnik z giełdy (Stawka własna)"], horizontal=True)
    
    detale_przewoznika = ""
    nazwa_przewoznika = ""

    if zrodlo == "Przewoźnik stały (Cennik)":
        f1, f2, f3, f4 = st.columns([2, 1, 1, 1])
        lista_cennikowa = list(slownik_stawek.keys()) if isinstance(slownik_stawek, dict) and slownik_stawek else ["Brak stawek"]
        nazwa_przewoznika = f1.selectbox("Wybierz partnera:", ["Wybierz..."] + lista_cennikowa)
        
        if nazwa_przewoznika != "Wybierz...":
            if not df_przewoznicy.empty and 'Skrócona Nazwa' in df_przewoznicy.columns:
                lista_nazw_w_bazie = df_przewoznicy['Skrócona Nazwa'].dropna().astype(str).tolist()
                najlepsze_dopasowania = difflib.get_close_matches(nazwa_przewoznika, lista_nazw_w_bazie, n=1, cutoff=0.4)
                
                if najlepsze_dopasowania:
                    dopasowana_nazwa = najlepsze_dopasowania[0]
                    row_p = df_przewoznicy[df_przewoznicy['Skrócona Nazwa'] == dopasowana_nazwa]
                    r = row_p.iloc[0]
                    detale_przewoznika = f"{str(r.get('Pełna Nazwa', dopasowana_nazwa))}\n{str(r.get('Ulica i numer', ''))}\n{str(r.get('Kod pocztowy i Miasto', ''))}, {str(r.get('Kraj', 'Polska'))}\nNIP: {str(r.get('NIP', ''))}".strip()
                    st.info(f"🔗 Połączono: **{dopasowana_nazwa}**")
                else:
                    detale_przewoznika = nazwa_przewoznika
            else: detale_przewoznika = nazwa_przewoznika

        dane_wybranego = slownik_stawek.get(nazwa_przewoznika, {"cost": 0.0, "postoj": 0.0}) if isinstance(slownik_stawek, dict) else {}
        stawka_final = f2.number_input("Cena Total:", value=float(dane_wybranego.get("cost", 0.0)))
        waluta = f3.selectbox("Waluta:", ["EUR", "PLN"])
        postoj = f4.number_input("Postój:", value=float(dane_wybranego.get("postoj", 0.0))) if typ_zlecenia == "Pełny event" else 0.0
            
    else:
        nazwa_przewoznika = st.text_input("Nazwa firmy z giełdy:")
        detale_przewoznika = st.text_area("Pełne dane (Adres, NIP):")
        f1, f2, f3 = st.columns(3)
        stawka_final = f1.number_input("Stawka netto:", min_value=0.0)
        waluta = f2.selectbox("Waluta:", ["EUR", "PLN"])
        postoj = f3.number_input("Postój:", min_value=0.0) if typ_zlecenia == "Pełny event" else 0.0

with st.container(border=True):
    st.markdown("#### 3. Logistyka Miejsc")
    projekt = st.selectbox("Przypisz do Projektu:", lista_eventow)
    l1, l2 = st.columns(2)
    with l1:
        z_sel = st.selectbox("Miejsce startu:", opcje_lokalizacji)
        z_man = st.text_input("Adres startu (ręcznie):") if z_sel == "INNE (wpisz ręcznie)" else ""
    with l2:
        r_sel = st.selectbox("Miejsce celu:", opcje_lokalizacji)
        r_man = st.text_input("Adres celu (ręcznie):") if r_sel == "INNE (wpisz ręcznie)" else ""

with st.container(border=True):
    st.markdown("#### 4. Realizacja i Uwagi")
    d_auto, d_wart = st.columns(2)
    c_auto = d_auto.text_input("Auto / Kierowca:", placeholder="np. PO 12345 / Jan Kowalski")
    wartosc_towaru = d_wart.number_input("Wartość towaru (PLN):", min_value=0, value=100000)
    u1, u2 = st.columns([3, 1])
    domyslny_tekst = "Parking strzeżony, pasy zabezpieczające; załadować po długości, casy nie mogą leżeć, kłódka / Guarded parking, safety belts; load lengthwise, cases cannot lie down, safe lock."
    instrukcje = u1.text_area("Instrukcje dodatkowe:", value=domyslny_tekst, height=80)
    podpis = u2.radio("Podpis:", ["PD", "PK"], horizontal=True)

if st.button("⚡ GENERUJ I ZAPISZ ZLECENIE PRO", type="primary", use_container_width=True):
    if not nazwa_przewoznika or nazwa_przewoznika == "Wybierz...":
        st.error("Podaj nazwę przewoźnika!")
    else:
        with st.spinner("Przetwarzanie..."):
            final_zal_db = z_man if z_sel == "INNE (wpisz ręcznie)" else z_sel
            final_roz_db = r_man if r_sel == "INNE (wpisz ręcznie)" else r_sel
            
            def build_full_address(place_name, manual_addr, df):
                if place_name == "INNE (wpisz ręcznie)": return manual_addr
                if place_name == "Magazyn SQM Komorniki":
                    return "SQM Prosta Spółka Akcyjna ;\nul. Poznańska 165, 62-052 Komorniki,\nNIP: 7792361182"
                if df is not None and not df.empty:
                    row = df[df['Nazwa do listy'] == place_name]
                    if not row.empty:
                        r = row.iloc[0]
                        return f"{r.get('Nazwa pełna / Firma', place_name)}\n{r.get('Ulica i numer', '')}\n{r.get('Kod pocztowy', '')} {r.get('Miasto', '')}, {r.get('Kraj', '')}"
                return place_name

            full_zal_pdf = build_full_address(z_sel, z_man, df_miejsca)
            full_roz_pdf = build_full_address(r_sel, r_man, df_miejsca)
            
            # --- KONSTRUKCJA PEŁNYCH UWAG (BAZA + PDF) ---
            historia_cyklu = f"CYKL: {data_zal} -> {data_roz}" + (f" | EMP: {data_emp_in} | POWRÓT: {data_emp_out}" if typ_zlecenia == "Pełny event" else "")
            
            # To trafi do bazy danych (kolumna uwagi)
            pelne_uwagi_db = f"AUTO: {c_auto} || WART: {wartosc_towaru} PLN || {historia_cyklu} || {instrukcje}"
            
            # To trafi na PDF (Sekcja Special Provisions)
            uwagi_na_pdf = f"VEHICLE/DRIVER: {c_auto}\n{instrukcje}"
            
            idx = get_next_daily_number(datetime.now().strftime("%Y-%m-%d"))
            nr_zlecenia = f"CRG{datetime.now().strftime('%y/%m%d')}/{podpis}{idx:02d}"
            
            paczka_pdf = {
                "typ_zlecenia": typ_zlecenia, "nr": nr_zlecenia, 
                "przewoznik_nazwa": nazwa_przewoznika, "przewoznik_detale": detale_przewoznika,
                "stawka": stawka_final, "waluta": waluta, "postoj": postoj,
                "zaladunek": full_zal_pdf, "data_zal": str(data_zal),
                "rozladunek": full_roz_pdf, "data_roz": str(data_roz),
                "data_emp_in": str(data_emp_in), "data_emp_out": str(data_emp_out),
                "waga": waga, "auto": c_auto, "uwagi": uwagi_na_pdf, "opiekun": podpis 
            }
            
            wiersz_db = [
                datetime.now().strftime("%Y-%m-%d %H:%M"), nr_zlecenia, "LOGISTYKA CARGO", nazwa_przewoznika,
                final_zal_db, final_roz_db, str(data_zal), str(data_roz), "Zabudowa Targowa PRO",
                "", "", "", "", pelne_uwagi_db, "", projekt, "TARGI", f"{stawka_final} {waluta}"
            ]
            
            if append_data("Zlecenia", wiersz_db):
                pdf_bytes = generate_pro_pdf(paczka_pdf)
                st.success(f"✅ Zlecenie {nr_zlecenia} zapisane z pełnymi uwagami!")
                st.download_button("📥 POBIERZ PDF", data=pdf_bytes, file_name=f"Order_{nr_zlecenia.replace('/', '_')}.pdf", mime="application/pdf", use_container_width=True)
